name: Update Lambda Layer

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  update-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python

      - name: Create Lambda layer zip
        run: |
          zip -r dependencies_layer.zip python

      - name: Upload layer to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'uu-north-1'
        run: |
          aws s3 cp dependencies_layer.zip s3://bucket-fastapi-test-dependencies-layer/dependencies_layer.zip

      - name: Publish Lambda layer
        id: publish_layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          aws lambda publish-layer-version --layer-name dependencies_layer --description "Dependencies for my lambda function" --content S3Bucket=fastapi-test-dependencies-layer,S3Key=dependencies_layer.zip --compatible-runtimes python3.8

      - name: Update Lambda function to use new layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          LAYER_VERSION_ARN=$(aws lambda list-layer-versions --layer-name dependencies_layer --query 'LayerVersions[0].LayerVersionArn' --output text)
          aws lambda update-function-configuration --function-name your_lambda_function_name --layers $LAYER_VERSION_ARN
