name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'requirements.txt'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'


      - name: Create deployment package
        run: |
          cd ..
          cd ..
          zip -r function.zip . -x ".*" -x "*/.*" -x "venv/*" -x "__pycache__/*" -x "*.pyc"


      - name: List S3 contents
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws s3 ls s3://bucket-fastapi-test/


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'

      - name: Upload to S3
        run: |
          aws s3 cp function.zip s3://bucket-fastapi-test/function.zip


      - name: List S3 contents new
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws s3 ls s3://bucket-fastapi-test/

      - name: Update Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws lambda update-function-code --function-name IDE-S3-Fastapi --s3-bucket bucket-fastapi-test --s3-key function.zip
