name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:


      - name: Zip code
        run: |
          zip -r function.zip .

      - name: Upload to S3
        uses: hkusu/s3-upload-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws s3 cp function.zip s3://bucket-fastapi-test/v1.0.0/function.zip

      - name: Update Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws lambda update-function-code --function-name IDE-S3-Fastapi --s3-bucket bucket-fastapi-test --s3-key v1.0.0/function.zip
