name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'requirements.txt'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'


      - name: Create deployment package
        run: |
          mkdir -p package
          cp -r * package/
          cd package
          zip -r ../function.zip .
          cd ..



      - uses: hkusu/s3-upload-action@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: 'eu-north-1'
            aws-bucket: 'bucket-fastapi-test'
            file-path: '../function.zip'


      - name: Update Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
        run: |
          aws lambda update-function-code --function-name IDE-S3-Fastapi --s3-bucket bucket-fastapi-test --s3-key function.zip
